`timescale 1ns/1ps
// =============================================================================
// ip_stubs.sv — Behavioural replacements for the two Vivado block-RAM IPs
//               that student_top.sv and dram_driver.sv instantiate.
//
// Port interfaces match the Vivado Block Memory Generator outputs exactly
// so that student_top.sv and dram_driver.sv compile unchanged in simulation.
//
// ── IROM ─────────────────────────────────────────────────────────────────────
//   Vivado port: IROM(.a(addr[13:0]), .spo(data[31:0]))
//   spo = asynchronous (combinatorial) output – no output register.
//   Capacity: 16 K words (14-bit address) = 64 KB.
//   Loaded from: irom_board.hex (generated by scripts/coe2hex.py from
//                reference_onecycle/irom.coe, 1549 words).
//   Word 0 (addr=0) → PC 0x8000_0000 = 0x00137117 (AUIPC x2, 0x137000).
//   Word 4 (addr=4) → PC 0x8000_0010 = 0x0000006f (JAL x0, 0 = halt loop).
//
// ── DRAM ─────────────────────────────────────────────────────────────────────
//   Vivado port: DRAM(.clk(clk), .a(addr[15:0]), .d(wdata[31:0]),
//                     .we(wen), .spo(rdata[31:0]))
//   spo = asynchronous read; write is registered on posedge clk.
//   Capacity: 64 K words (16-bit address) = 256 KB.
//   Loaded from: dram_board.hex (generated by scripts/coe2hex.py from
//                reference_onecycle/dram.coe, 12 words).
//   Notable pre-loaded values:
//     word  3 (byte addr 0x8010_000C) = 0x1234_abcd
//     word  4 (byte addr 0x8010_0010) = 0x5566_7788
//     word  7 (byte addr 0x8010_001C) = 0xff00_00ff
//
// ── seg7 ──────────────────────────────────────────────────────────────────────
//   Needed by display_seg.sv (rtl/) which is instantiated in perip_bridge.sv.
//   The seg7 module is not in rtl/; it lives in reference_onecycle/.
//   Included here to keep all simulation-only helpers in one file.
// =============================================================================

// -----------------------------------------------------------------------------
// IROM — 16 K × 32-bit asynchronous instruction ROM
// -----------------------------------------------------------------------------
module IROM (
    input  wire [13:0] a,    // word address (pc[15:2])
    output wire [31:0] spo   // asynchronous data output
);
    reg [31:0] mem [0:16383];

    initial begin
        // Zero-fill first so any address beyond the .coe content reads 0.
        integer idx;
        for (idx = 0; idx < 16384; idx = idx + 1)
            mem[idx] = 32'h0000_0013;   // NOP (ADDI x0,x0,0) — safe default

        // Load 1547 instruction words from irom.coe (converted to hex).
        // Explicit range [0:1546] suppresses the "not enough words" warning
        // that iverilog emits when the array is larger than the file.
        // File must be in the simulator working directory (run from tb/).
        $readmemh("irom_board.hex", mem, 0, 1546);
    end

    assign spo = mem[a];
endmodule


// -----------------------------------------------------------------------------
// DRAM — 64 K × 32-bit synchronous-write / asynchronous-read data RAM
// -----------------------------------------------------------------------------
module DRAM (
    input  wire        clk,
    input  wire [15:0] a,    // word address (byte_addr[17:2] from dram_driver)
    input  wire [31:0] d,    // merged write word (from dram_driver merge logic)
    input  wire        we,   // write enable (already qualified by perip_bridge)
    output wire [31:0] spo   // asynchronous data output
);
    reg [31:0] mem [0:65535];

    initial begin
        integer idx;
        for (idx = 0; idx < 65536; idx = idx + 1)
            mem[idx] = 32'h0000_0000;

        // Load 12 data words from dram.coe (converted to hex).
        // Explicit range suppresses the iverilog "not enough words" warning.
        // File must be in the simulator working directory (run from tb/).
        $readmemh("dram_board.hex", mem, 0, 11);
    end

    assign spo = mem[a];   // asynchronous read — mirrors Vivado spo behaviour

    always @(posedge clk) begin
        if (we)
            mem[a] <= d;   // dram_driver already computed the merged word
    end
endmodule


// -----------------------------------------------------------------------------
// seg7 — 4-bit hex digit to 7-segment decoder
// Required by display_seg (rtl/display_seg.sv instantiates four of these).
// Encoding: seg[6:0] = {g,f,e,d,c,b,a} — active high, common-cathode style.
// Identical to reference_onecycle/seg7_reference.sv.
// -----------------------------------------------------------------------------
module seg7 (
    input  wire [3:0] din,
    output reg  [6:0] dout
);
    always @(*) begin
        case (din)
            4'h0: dout = 7'b011_1111;
            4'h1: dout = 7'b000_0110;
            4'h2: dout = 7'b101_1011;
            4'h3: dout = 7'h4f;
            4'h4: dout = 7'h66;
            4'h5: dout = 7'h6d;
            4'h6: dout = 7'h7d;
            4'h7: dout = 7'h07;
            4'h8: dout = 7'h7f;
            4'h9: dout = 7'h6f;
            4'ha: dout = 7'h77;
            4'hb: dout = 7'h7c;
            4'hc: dout = 7'h39;
            4'hd: dout = 7'h5e;
            4'he: dout = 7'h79;
            4'hf: dout = 7'h71;
            default: dout = 7'h00;
        endcase
    end
endmodule
